/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.storagesync.v2018_04_02.implementation;

import com.microsoft.azure.arm.resources.models.implementation.GroupableResourceCoreImpl;
import com.microsoft.azure.management.storagesync.v2018_04_02.StorageSyncService;
import rx.Observable;
import com.microsoft.azure.management.storagesync.v2018_04_02.StorageSyncServiceUpdateParameters;
import rx.functions.Func1;

class StorageSyncServiceImpl extends GroupableResourceCoreImpl<StorageSyncService, StorageSyncServiceInner, StorageSyncServiceImpl, StorageSyncManager> implements StorageSyncService, StorageSyncService.Definition, StorageSyncService.Update {
    private StorageSyncServiceUpdateParameters updateParameter;
    StorageSyncServiceImpl(String name, StorageSyncServiceInner inner, StorageSyncManager manager) {
        super(name, inner, manager);
        this.updateParameter = new StorageSyncServiceUpdateParameters();
    }

    @Override
    public Observable<StorageSyncService> createResourceAsync() {
        StorageSyncServicesInner client = this.manager().inner().storageSyncServices();
        return client.createAsync(this.resourceGroupName(), this.name(), this.inner())
            .map(new Func1<StorageSyncServiceInner, StorageSyncServiceInner>() {
               @Override
               public StorageSyncServiceInner call(StorageSyncServiceInner resource) {
                   resetCreateUpdateParameters();
                   return resource;
               }
            })
            .map(innerToFluentMap(this));
    }

    @Override
    public Observable<StorageSyncService> updateResourceAsync() {
        StorageSyncServicesInner client = this.manager().inner().storageSyncServices();
        return client.updateAsync(this.resourceGroupName(), this.name(), this.updateParameter)
            .map(new Func1<StorageSyncServiceInner, StorageSyncServiceInner>() {
               @Override
               public StorageSyncServiceInner call(StorageSyncServiceInner resource) {
                   resetCreateUpdateParameters();
                   return resource;
               }
            })
            .map(innerToFluentMap(this));
    }

    @Override
    protected Observable<StorageSyncServiceInner> getInnerAsync() {
        StorageSyncServicesInner client = this.manager().inner().storageSyncServices();
        return client.getByResourceGroupAsync(this.resourceGroupName(), this.name());
    }

    @Override
    public boolean isInCreateMode() {
        return this.inner().id() == null;
    }

    private void resetCreateUpdateParameters() {
        this.updateParameter = new StorageSyncServiceUpdateParameters();
    }

    @Override
    public Integer storageSyncServiceStatus() {
        return this.inner().storageSyncServiceStatus();
    }

    @Override
    public String storageSyncServiceUid() {
        return this.inner().storageSyncServiceUid();
    }

    @Override
    public StorageSyncServiceImpl withProperties(Object properties) {
        this.updateParameter.withProperties(properties);
        return this;
    }

}
