/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.storagesync.v2018_04_02;

import com.microsoft.azure.arm.model.HasInner;
import com.microsoft.azure.management.storagesync.v2018_04_02.implementation.CloudEndpointInner;
import com.microsoft.azure.arm.model.Indexable;
import com.microsoft.azure.arm.model.Refreshable;
import com.microsoft.azure.arm.model.Updatable;
import com.microsoft.azure.arm.model.Appliable;
import com.microsoft.azure.arm.model.Creatable;
import com.microsoft.azure.arm.resources.models.HasManager;
import com.microsoft.azure.management.storagesync.v2018_04_02.implementation.StorageSyncManager;

/**
 * Type representing CloudEndpoint.
 */
public interface CloudEndpoint extends HasInner<CloudEndpointInner>, Indexable, Refreshable<CloudEndpoint>, Updatable<CloudEndpoint.Update>, HasManager<StorageSyncManager> {
    /**
     * @return the backupEnabled value.
     */
    Boolean backupEnabled();

    /**
     * @return the friendlyName value.
     */
    String friendlyName();

    /**
     * @return the id value.
     */
    String id();

    /**
     * @return the lastOperationName value.
     */
    String lastOperationName();

    /**
     * @return the lastWorkflowId value.
     */
    String lastWorkflowId();

    /**
     * @return the name value.
     */
    String name();

    /**
     * @return the partnershipId value.
     */
    String partnershipId();

    /**
     * @return the provisioningState value.
     */
    String provisioningState();

    /**
     * @return the storageAccount value.
     */
    String storageAccount();

    /**
     * @return the storageAccountKey value.
     */
    String storageAccountKey();

    /**
     * @return the storageAccountResourceId value.
     */
    String storageAccountResourceId();

    /**
     * @return the storageAccountShareName value.
     */
    String storageAccountShareName();

    /**
     * @return the storageAccountTenantId value.
     */
    String storageAccountTenantId();

    /**
     * @return the type value.
     */
    String type();

    /**
     * The entirety of the CloudEndpoint definition.
     */
    interface Definition extends DefinitionStages.Blank, DefinitionStages.WithSyncGroup, DefinitionStages.WithCreate {
    }

    /**
     * Grouping of CloudEndpoint definition stages.
     */
    interface DefinitionStages {
        /**
         * The first stage of a CloudEndpoint definition.
         */
        interface Blank extends WithSyncGroup {
        }

        /**
         * The stage of the cloudendpoint definition allowing to specify SyncGroup.
         */
        interface WithSyncGroup {
           /**
            * Specifies resourceGroupName, storageSyncServiceName, syncGroupName.
            * @param resourceGroupName The name of the resource group. The name is case insensitive
            * @param storageSyncServiceName Name of Storage Sync Service resource
            * @param syncGroupName Name of Sync Group resource
            * @return the next definition stage
            */
            WithCreate withExistingSyncGroup(String resourceGroupName, String storageSyncServiceName, String syncGroupName);
        }

        /**
         * The stage of the cloudendpoint definition allowing to specify FriendlyName.
         */
        interface WithFriendlyName {
            /**
             * Specifies friendlyName.
             * @param friendlyName Friendly Name
             * @return the next definition stage
             */
            WithCreate withFriendlyName(String friendlyName);
        }

        /**
         * The stage of the cloudendpoint definition allowing to specify LastOperationName.
         */
        interface WithLastOperationName {
            /**
             * Specifies lastOperationName.
             * @param lastOperationName Resource Last Operation Name
             * @return the next definition stage
             */
            WithCreate withLastOperationName(String lastOperationName);
        }

        /**
         * The stage of the cloudendpoint definition allowing to specify LastWorkflowId.
         */
        interface WithLastWorkflowId {
            /**
             * Specifies lastWorkflowId.
             * @param lastWorkflowId CloudEndpoint lastWorkflowId
             * @return the next definition stage
             */
            WithCreate withLastWorkflowId(String lastWorkflowId);
        }

        /**
         * The stage of the cloudendpoint definition allowing to specify PartnershipId.
         */
        interface WithPartnershipId {
            /**
             * Specifies partnershipId.
             * @param partnershipId Partnership Id
             * @return the next definition stage
             */
            WithCreate withPartnershipId(String partnershipId);
        }

        /**
         * The stage of the cloudendpoint definition allowing to specify ProvisioningState.
         */
        interface WithProvisioningState {
            /**
             * Specifies provisioningState.
             * @param provisioningState CloudEndpoint Provisioning State
             * @return the next definition stage
             */
            WithCreate withProvisioningState(String provisioningState);
        }

        /**
         * The stage of the cloudendpoint definition allowing to specify StorageAccount.
         */
        interface WithStorageAccount {
            /**
             * Specifies storageAccount.
             * @param storageAccount Storage Account name
             * @return the next definition stage
             */
            WithCreate withStorageAccount(String storageAccount);
        }

        /**
         * The stage of the cloudendpoint definition allowing to specify StorageAccountKey.
         */
        interface WithStorageAccountKey {
            /**
             * Specifies storageAccountKey.
             * @param storageAccountKey Storage Account access key
             * @return the next definition stage
             */
            WithCreate withStorageAccountKey(String storageAccountKey);
        }

        /**
         * The stage of the cloudendpoint definition allowing to specify StorageAccountResourceId.
         */
        interface WithStorageAccountResourceId {
            /**
             * Specifies storageAccountResourceId.
             * @param storageAccountResourceId Storage Account Resource Id
             * @return the next definition stage
             */
            WithCreate withStorageAccountResourceId(String storageAccountResourceId);
        }

        /**
         * The stage of the cloudendpoint definition allowing to specify StorageAccountShareName.
         */
        interface WithStorageAccountShareName {
            /**
             * Specifies storageAccountShareName.
             * @param storageAccountShareName Storage Account Share name
             * @return the next definition stage
             */
            WithCreate withStorageAccountShareName(String storageAccountShareName);
        }

        /**
         * The stage of the cloudendpoint definition allowing to specify StorageAccountTenantId.
         */
        interface WithStorageAccountTenantId {
            /**
             * Specifies storageAccountTenantId.
             * @param storageAccountTenantId Storage Account Tenant Id
             * @return the next definition stage
             */
            WithCreate withStorageAccountTenantId(String storageAccountTenantId);
        }

        /**
         * The stage of the definition which contains all the minimum required inputs for
         * the resource to be created (via {@link WithCreate#create()}), but also allows
         * for any other optional settings to be specified.
         */
        interface WithCreate extends Creatable<CloudEndpoint>, DefinitionStages.WithFriendlyName, DefinitionStages.WithLastOperationName, DefinitionStages.WithLastWorkflowId, DefinitionStages.WithPartnershipId, DefinitionStages.WithProvisioningState, DefinitionStages.WithStorageAccount, DefinitionStages.WithStorageAccountKey, DefinitionStages.WithStorageAccountResourceId, DefinitionStages.WithStorageAccountShareName, DefinitionStages.WithStorageAccountTenantId {
        }
    }
    /**
     * The template for a CloudEndpoint update operation, containing all the settings that can be modified.
     */
    interface Update extends Appliable<CloudEndpoint>, UpdateStages.WithFriendlyName, UpdateStages.WithLastOperationName, UpdateStages.WithLastWorkflowId, UpdateStages.WithPartnershipId, UpdateStages.WithProvisioningState, UpdateStages.WithStorageAccount, UpdateStages.WithStorageAccountKey, UpdateStages.WithStorageAccountResourceId, UpdateStages.WithStorageAccountShareName, UpdateStages.WithStorageAccountTenantId {
    }

    /**
     * Grouping of CloudEndpoint update stages.
     */
    interface UpdateStages {
        /**
         * The stage of the cloudendpoint update allowing to specify FriendlyName.
         */
        interface WithFriendlyName {
            /**
             * Specifies friendlyName.
             * @param friendlyName Friendly Name
             * @return the next update stage
             */
            Update withFriendlyName(String friendlyName);
        }

        /**
         * The stage of the cloudendpoint update allowing to specify LastOperationName.
         */
        interface WithLastOperationName {
            /**
             * Specifies lastOperationName.
             * @param lastOperationName Resource Last Operation Name
             * @return the next update stage
             */
            Update withLastOperationName(String lastOperationName);
        }

        /**
         * The stage of the cloudendpoint update allowing to specify LastWorkflowId.
         */
        interface WithLastWorkflowId {
            /**
             * Specifies lastWorkflowId.
             * @param lastWorkflowId CloudEndpoint lastWorkflowId
             * @return the next update stage
             */
            Update withLastWorkflowId(String lastWorkflowId);
        }

        /**
         * The stage of the cloudendpoint update allowing to specify PartnershipId.
         */
        interface WithPartnershipId {
            /**
             * Specifies partnershipId.
             * @param partnershipId Partnership Id
             * @return the next update stage
             */
            Update withPartnershipId(String partnershipId);
        }

        /**
         * The stage of the cloudendpoint update allowing to specify ProvisioningState.
         */
        interface WithProvisioningState {
            /**
             * Specifies provisioningState.
             * @param provisioningState CloudEndpoint Provisioning State
             * @return the next update stage
             */
            Update withProvisioningState(String provisioningState);
        }

        /**
         * The stage of the cloudendpoint update allowing to specify StorageAccount.
         */
        interface WithStorageAccount {
            /**
             * Specifies storageAccount.
             * @param storageAccount Storage Account name
             * @return the next update stage
             */
            Update withStorageAccount(String storageAccount);
        }

        /**
         * The stage of the cloudendpoint update allowing to specify StorageAccountKey.
         */
        interface WithStorageAccountKey {
            /**
             * Specifies storageAccountKey.
             * @param storageAccountKey Storage Account access key
             * @return the next update stage
             */
            Update withStorageAccountKey(String storageAccountKey);
        }

        /**
         * The stage of the cloudendpoint update allowing to specify StorageAccountResourceId.
         */
        interface WithStorageAccountResourceId {
            /**
             * Specifies storageAccountResourceId.
             * @param storageAccountResourceId Storage Account Resource Id
             * @return the next update stage
             */
            Update withStorageAccountResourceId(String storageAccountResourceId);
        }

        /**
         * The stage of the cloudendpoint update allowing to specify StorageAccountShareName.
         */
        interface WithStorageAccountShareName {
            /**
             * Specifies storageAccountShareName.
             * @param storageAccountShareName Storage Account Share name
             * @return the next update stage
             */
            Update withStorageAccountShareName(String storageAccountShareName);
        }

        /**
         * The stage of the cloudendpoint update allowing to specify StorageAccountTenantId.
         */
        interface WithStorageAccountTenantId {
            /**
             * Specifies storageAccountTenantId.
             * @param storageAccountTenantId Storage Account Tenant Id
             * @return the next update stage
             */
            Update withStorageAccountTenantId(String storageAccountTenantId);
        }

    }
}
