/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.storagesync.v2018_04_02;

import com.microsoft.azure.arm.collection.SupportsCreating;
import rx.Completable;
import rx.Observable;
import com.microsoft.azure.management.storagesync.v2018_04_02.implementation.ServerEndpointsInner;
import com.microsoft.azure.arm.model.HasInner;

/**
 * Type representing ServerEndpoints.
 */
public interface ServerEndpoints extends SupportsCreating<ServerEndpoint.DefinitionStages.Blank>, HasInner<ServerEndpointsInner> {
    /**
     * Recall a serverendpoint.
     *
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param storageSyncServiceName Name of Storage Sync Service resource.
     * @param syncGroupName Name of Sync Group resource.
     * @param serverEndpointName Name of Server Endpoint object.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable for the request
     */
    Completable recallActionAsync(String resourceGroupName, String storageSyncServiceName, String syncGroupName, String serverEndpointName);

    /**
     * Get a ServerEndpoint.
     *
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param storageSyncServiceName Name of Storage Sync Service resource.
     * @param syncGroupName Name of Sync Group resource.
     * @param serverEndpointName Name of Server Endpoint object.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable for the request
     */
    Observable<ServerEndpoint> getAsync(String resourceGroupName, String storageSyncServiceName, String syncGroupName, String serverEndpointName);

    /**
     * Get a ServerEndpoint list.
     *
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param storageSyncServiceName Name of Storage Sync Service resource.
     * @param syncGroupName Name of Sync Group resource.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable for the request
     */
    Observable<ServerEndpoint> listBySyncGroupAsync(String resourceGroupName, String storageSyncServiceName, String syncGroupName);

    /**
     * Delete a given ServerEndpoint.
     *
     * @param resourceGroupName The name of the resource group. The name is case insensitive.
     * @param storageSyncServiceName Name of Storage Sync Service resource.
     * @param syncGroupName Name of Sync Group resource.
     * @param serverEndpointName Name of Server Endpoint object.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable for the request
     */
    Completable deleteAsync(String resourceGroupName, String storageSyncServiceName, String syncGroupName, String serverEndpointName);

}
