/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.storagesync.v2018_04_02;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Error type.
 */
public class StorageSyncError {
    /**
     * Error code of the given entry.
     */
    @JsonProperty(value = "code")
    private String code;

    /**
     * Error message of the given entry.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * Error details of the given entry.
     */
    @JsonProperty(value = "details")
    private StorageSyncErrorDetails details;

    /**
     * Get error code of the given entry.
     *
     * @return the code value
     */
    public String code() {
        return this.code;
    }

    /**
     * Set error code of the given entry.
     *
     * @param code the code value to set
     * @return the StorageSyncError object itself.
     */
    public StorageSyncError withCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get error message of the given entry.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set error message of the given entry.
     *
     * @param message the message value to set
     * @return the StorageSyncError object itself.
     */
    public StorageSyncError withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get error details of the given entry.
     *
     * @return the details value
     */
    public StorageSyncErrorDetails details() {
        return this.details;
    }

    /**
     * Set error details of the given entry.
     *
     * @param details the details value to set
     * @return the StorageSyncError object itself.
     */
    public StorageSyncError withDetails(StorageSyncErrorDetails details) {
        this.details = details;
        return this;
    }

}
